# DOCTORS 

# api call for listing doctors 

###
GET http://127.0.0.1:8000/doctors/
Accept: application/json


# api call for creating doctor

###
POST http://127.0.0.1:8000/doctors/
Content-Type: application/json

{
    "name":"ajith",
    "specialization":"uro",
    "fee":1000,
    "qualification":"mbbs",
    "email":"ajith@gamil.com"
}

# api call for listing specific doctor

###
GET http://127.0.0.1:8000/doctors/2/
Accept: application/json

###
PUT http://127.0.0.1:8000/doctors/2/
Content-Type: application/json

{
    "name": "naveen",
    "specialization": "urology",
    "fee": 1200,
    "qualification": "mbbs",
    "email": "naveen@gamil.com"
}

# api call for deleting doctor

###
DELETE http://127.0.0.1:8000/doctors/2/
Accept: application/json


# staff_v2

# api call for listing doctors 

###
GET http://127.0.0.1:8000/v2/doctors/
Accept: application/json

# api call for creating doctor

###
POST http://127.0.0.1:8000/v2/doctors/
Content-Type: application/json

{
    "name":"anaghesh",
    "specialization":"uro",
    "fee":1000,
    "qualification":"mbbs",
    "email":"anaghesh@gamil.com"
}

# api call for listing specific doctor

###
GET http://127.0.0.1:8000/v2/doctors/3/
Accept: application/json

# api call for updating


###
PUT http://127.0.0.1:8000/v2/doctors/3/
Content-Type: application/json

{
    "id":3,
    "name": "anaghesh k a",
    "specialization": "urology",
    "fee": 900,
    "qualification": "mbbs",
    "email": "anaghesh@gamil.com"
}

# api call for creating admin

###
POST http://127.0.0.1:8000/v2/admin-register/
Content-Type: application/json

{
    "username":"superuser",
    "email":"superuser@gmail.com",
    "password":"superuser"
}


# APPOINTMENTS ===================================


#api call for listing all appointments

###
GET  http://127.0.0.1:8000/appointments/
Accept: application/json


# api call for creating appointments

###
POST http://127.0.0.1:8000/appointments/
Content-Type: application/json

{
    "patient_name":"Rahul",
    "phone":"123456789",
    "doctor":1,
    "appointment_date":"2026-10-02",
    "problem":"weezing"
}



# booking_v2 ================================

# api call for creating booking
###
POST http://127.0.0.1:8000/v2/booking/signup/
Content-Type: application/json

{
    "username":"django",
    "email":"django@gmail.com",
    "password":"django"
}